import { hero1, hero2, hero3, hero4, hero5, hero6 } from "../assets";
import { StockShoes } from "../hooks/useStock";

export const mockStockShoes: StockShoes[] = [
  {
    id: 1,
    name: "Nike Dunk High Retro",
    brand: "Nike",
    category: "Men",
    main_picture: hero1,
    images: [hero1, hero2, hero3],
    price: 2999,
    size_range: "40-45",
    stock: "15",
    uid: "nike-dunk-high-retro-1",
    description: "Classic Nike Dunk High with premium materials and comfortable fit. Perfect for everyday wear and casual outings.",
  },
  {
    id: 2,
    name: "Nike Dunk High Premium",
    brand: "Nike",
    category: "Men",
    main_picture: hero2,
    images: [hero2, hero1, hero4],
    price: 3299,
    size_range: "40-45",
    stock: "12",
    uid: "nike-dunk-high-premium-2",
    description: "Premium version of the classic Nike Dunk High with enhanced comfort and durability.",
  },
  {
    id: 3,
    name: "Nike Dunk High SE",
    brand: "Nike",
    category: "Women",
    main_picture: hero3,
    images: [hero3, hero5, hero6],
    price: 2999,
    size_range: "36-42",
    stock: "18",
    uid: "nike-dunk-high-se-3",
    description: "Special edition Nike Dunk High designed for women with stylish colorways and modern design.",
  },
  {
    id: 4,
    name: "Air Jordan 3 Retro",
    brand: "Jordan",
    category: "Men",
    main_picture: hero4,
    images: [hero4, hero1, hero2],
    price: 4999,
    size_range: "40-45",
    stock: "8",
    uid: "air-jordan-3-retro-4",
    description: "Iconic Air Jordan 3 Retro with visible air cushioning and elephant print. A timeless classic.",
  },
  {
    id: 5,
    name: "Nike Dunk Low SE",
    brand: "Nike",
    category: "Women",
    main_picture: hero5,
    images: [hero5, hero3, hero1],
    price: 3999,
    size_range: "36-42",
    stock: "14",
    uid: "nike-dunk-low-se-5",
    description: "Special edition Nike Dunk Low with unique colorway and premium materials for ultimate comfort.",
  },
  {
    id: 6,
    name: "Air Jordan 1 Mid SE",
    brand: "Jordan",
    category: "Kids",
    main_picture: hero6,
    images: [hero6, hero4, hero2],
    price: 5999,
    size_range: "30-38",
    stock: "10",
    uid: "air-jordan-1-mid-se-6",
    description: "Special edition Air Jordan 1 Mid with modern design and classic style. Perfect for kids.",
  },
  {
    id: 7,
    name: "Nike Dunk High OG",
    brand: "Nike",
    category: "Men",
    main_picture: hero1,
    images: [hero1, hero3, hero5],
    price: 3499,
    size_range: "40-45",
    stock: "11",
    uid: "nike-dunk-high-og-7",
    description: "Original Nike Dunk High with authentic design and premium construction.",
  },
  {
    id: 8,
    name: "Air Jordan 4 Retro",
    brand: "Jordan",
    category: "Women",
    main_picture: hero2,
    images: [hero2, hero4, hero6],
    price: 5499,
    size_range: "36-42",
    stock: "9",
    uid: "air-jordan-4-retro-8",
    description: "Retro Air Jordan 4 with classic design and modern comfort features.",
  },
  {
    id: 9,
    name: "Nike Dunk Low Kids",
    brand: "Nike",
    category: "Kids",
    main_picture: hero3,
    images: [hero3, hero1, hero5],
    price: 2499,
    size_range: "30-38",
    stock: "16",
    uid: "nike-dunk-low-kids-9",
    description: "Perfect for kids, comfortable and stylish Nike Dunk Low with vibrant colors.",
  },
  {
    id: 10,
    name: "Air Jordan 1 High OG",
    brand: "Jordan",
    category: "Men",
    main_picture: hero4,
    images: [hero4, hero2, hero6],
    price: 6499,
    size_range: "40-45",
    stock: "7",
    uid: "air-jordan-1-high-og-10",
    description: "Original Air Jordan 1 High with iconic design and premium leather construction.",
  },
  {
    id: 11,
    name: "Nike Dunk High Women",
    brand: "Nike",
    category: "Women",
    main_picture: hero5,
    images: [hero5, hero3, hero1],
    price: 3199,
    size_range: "36-42",
    stock: "13",
    uid: "nike-dunk-high-women-11",
    description: "Stylish Nike Dunk High designed specifically for women with elegant colorways.",
  },
  {
    id: 12,
    name: "Air Jordan 5 Retro",
    brand: "Jordan",
    category: "Men",
    main_picture: hero6,
    images: [hero6, hero4, hero2],
    price: 5799,
    size_range: "40-45",
    stock: "6",
    uid: "air-jordan-5-retro-12",
    description: "Retro Air Jordan 5 with distinctive design elements and superior comfort.",
  },
  {
    id: 13,
    name: "Nike Dunk Low Men",
    brand: "Nike",
    category: "Men",
    main_picture: hero1,
    images: [hero1, hero2, hero3],
    price: 2799,
    size_range: "40-45",
    stock: "17",
    uid: "nike-dunk-low-men-13",
    description: "Classic Nike Dunk Low for men with versatile design and comfortable fit.",
  },
  {
    id: 14,
    name: "Air Jordan 6 Retro",
    brand: "Jordan",
    category: "Women",
    main_picture: hero2,
    images: [hero2, hero5, hero6],
    price: 5299,
    size_range: "36-42",
    stock: "8",
    uid: "air-jordan-6-retro-14",
    description: "Retro Air Jordan 6 with sleek design and advanced cushioning technology.",
  },
  {
    id: 15,
    name: "Nike Dunk High Kids Edition",
    brand: "Nike",
    category: "Kids",
    main_picture: hero3,
    images: [hero3, hero4, hero1],
    price: 2299,
    size_range: "30-38",
    stock: "20",
    uid: "nike-dunk-high-kids-15",
    description: "Fun and colorful Nike Dunk High designed for kids with playful patterns.",
  },
  {
    id: 16,
    name: "Air Jordan 2 Retro",
    brand: "Jordan",
    category: "Men",
    main_picture: hero4,
    images: [hero4, hero1, hero3],
    price: 4699,
    size_range: "40-45",
    stock: "9",
    uid: "air-jordan-2-retro-16",
    description: "Retro Air Jordan 2 with premium materials and classic basketball heritage.",
  },
  {
    id: 17,
    name: "Nike Dunk Low Women Premium",
    brand: "Nike",
    category: "Women",
    main_picture: hero5,
    images: [hero5, hero2, hero4],
    price: 3699,
    size_range: "36-42",
    stock: "15",
    uid: "nike-dunk-low-women-premium-17",
    description: "Premium Nike Dunk Low for women with luxurious materials and elegant styling.",
  },
  {
    id: 18,
    name: "Air Jordan 7 Retro",
    brand: "Jordan",
    category: "Kids",
    main_picture: hero6,
    images: [hero6, hero3, hero5],
    price: 4499,
    size_range: "30-38",
    stock: "11",
    uid: "air-jordan-7-retro-kids-18",
    description: "Retro Air Jordan 7 designed for kids with vibrant colors and comfortable fit.",
  },
  {
    id: 19,
    name: "Nike Dunk High Sport",
    brand: "Nike",
    category: "Men",
    main_picture: hero1,
    images: [hero1, hero4, hero6],
    price: 3399,
    size_range: "40-45",
    stock: "12",
    uid: "nike-dunk-high-sport-19",
    description: "Sport-focused Nike Dunk High with enhanced performance features and durability.",
  },
  {
    id: 20,
    name: "Air Jordan 8 Retro",
    brand: "Jordan",
    category: "Women",
    main_picture: hero2,
    images: [hero2, hero1, hero3],
    price: 5199,
    size_range: "36-42",
    stock: "7",
    uid: "air-jordan-8-retro-20",
    description: "Retro Air Jordan 8 with unique design elements and superior comfort.",
  },
  {
    id: 21,
    name: "Nike Dunk Low Classic",
    brand: "Nike",
    category: "Men",
    main_picture: hero3,
    images: [hero3, hero5, hero1],
    price: 2899,
    size_range: "40-45",
    stock: "19",
    uid: "nike-dunk-low-classic-21",
    description: "Classic Nike Dunk Low with timeless design and versatile styling options.",
  },
  {
    id: 22,
    name: "Air Jordan 9 Retro",
    brand: "Jordan",
    category: "Kids",
    main_picture: hero4,
    images: [hero4, hero6, hero2],
    price: 4399,
    size_range: "30-38",
    stock: "13",
    uid: "air-jordan-9-retro-kids-22",
    description: "Retro Air Jordan 9 for kids with playful design and comfortable construction.",
  },
  {
    id: 23,
    name: "Nike Dunk High Fashion",
    brand: "Nike",
    category: "Women",
    main_picture: hero5,
    images: [hero5, hero3, hero6],
    price: 3599,
    size_range: "36-42",
    stock: "14",
    uid: "nike-dunk-high-fashion-23",
    description: "Fashion-forward Nike Dunk High for women with trendy colorways and modern aesthetics.",
  },
  {
    id: 24,
    name: "Air Jordan 10 Retro",
    brand: "Jordan",
    category: "Men",
    main_picture: hero6,
    images: [hero6, hero4, hero1],
    price: 5999,
    size_range: "40-45",
    stock: "5",
    uid: "air-jordan-10-retro-24",
    description: "Retro Air Jordan 10 with innovative design and premium quality materials.",
  },
  {
    id: 25,
    name: "Nike Dunk Low Street",
    brand: "Nike",
    category: "Men",
    main_picture: hero1,
    images: [hero1, hero2, hero4],
    price: 2699,
    size_range: "40-45",
    stock: "21",
    uid: "nike-dunk-low-street-25",
    description: "Street-style Nike Dunk Low with urban aesthetics and comfortable everyday wear.",
  },
  {
    id: 26,
    name: "Air Jordan 11 Retro",
    brand: "Jordan",
    category: "Women",
    main_picture: hero2,
    images: [hero2, hero5, hero3],
    price: 5699,
    size_range: "36-42",
    stock: "6",
    uid: "air-jordan-11-retro-26",
    description: "Retro Air Jordan 11 with patent leather accents and iconic design elements.",
  },
  {
    id: 27,
    name: "Nike Dunk High Kids Sport",
    brand: "Nike",
    category: "Kids",
    main_picture: hero3,
    images: [hero3, hero1, hero6],
    price: 2199,
    size_range: "30-38",
    stock: "22",
    uid: "nike-dunk-high-kids-sport-27",
    description: "Sporty Nike Dunk High for kids with fun colors and durable construction for active play.",
  },
  {
    id: 28,
    name: "Air Jordan 12 Retro",
    brand: "Jordan",
    category: "Men",
    main_picture: hero4,
    images: [hero4, hero2, hero5],
    price: 5899,
    size_range: "40-45",
    stock: "8",
    uid: "air-jordan-12-retro-28",
    description: "Retro Air Jordan 12 with premium materials and advanced cushioning technology.",
  },
  {
    id: 29,
    name: "Nike Dunk Low Women Classic",
    brand: "Nike",
    category: "Women",
    main_picture: hero5,
    images: [hero5, hero4, hero2],
    price: 3099,
    size_range: "36-42",
    stock: "16",
    uid: "nike-dunk-low-women-classic-29",
    description: "Classic Nike Dunk Low for women with elegant design and comfortable fit.",
  },
  {
    id: 30,
    name: "Air Jordan 13 Retro",
    brand: "Jordan",
    category: "Kids",
    main_picture: hero6,
    images: [hero6, hero3, hero1],
    price: 4299,
    size_range: "30-38",
    stock: "12",
    uid: "air-jordan-13-retro-kids-30",
    description: "Retro Air Jordan 13 for kids with unique design and comfortable fit for all-day wear.",
  },
];

export default mockStockShoes;

